### ISSUE TITLE
Invalid dimension nether:nether_new

### ISSUE THREAD

**Issue by shoya420** [Codecrafter14/netherupdatemod#1]
Let me preface this with some extra information.

One of the new nether biomes conflicted with a Biome Bundle biome, ID 40, crashing my game. I changed the ID of the Biome Bundle biome to 643. This fixed the that issue. Some changes to the ID could make this mod compatible with biome mods, or at least Biome Bundle. I think at least... I really don't know sh*t. Definitely not necessary because I pretty easily changed the ID.

After fixing that I went to create a new world.

When creating a new world I get this error:

The game crashed whilst exception in server tick loop
Error: java.lang.IllegalArgumentException: Invalid dimension nether:nether_new
Exit Code: -1

If you'd like the full crash report:
[crash-2021-06-10_22.48.26-server.txt](https://github.com/Codecrafter14/netherupdatemod/files/6635938/crash-2021-06-10_22.48.26-server.txt)

**Comment by Codecrafter14** [comment]
Hello, this bug has been fixed in update 3.0.0 of the mod. There was an advancement that crashed the game. Thank you for the bug report!
